name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        tox

    - name: Build executable
      run: |
        pyinstaller src/main.py

    - name: Create zip file
      run: |
        powershell Compress-Archive -Path dist\* -DestinationPath dist\main.zip

    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/main.zip
        token: ${{ secrets.RELEASE_ACTION_TOKEN }}
        name: ${{ github.ref }}
        body: |
          Release for ${{ github.ref }}
          - [main.zip]
